### ISSUE TITLE
[Issue] Crash with the Latest version (10 min ago lmao)

### ISSUE THREAD

**Issue by Leclowndu93150** [nanite/Trenzalore#2]
### Minecraft Version

1.20.1

### Modloader

47.1.3

### Mod version

latest

### Latest version?

- [X] Yes

### Repeatable?

- [ ] Yes

### Link to log files

wrong log lemme reupload

### Steps to reproduce the issue

i have no clue but the upgrade broke my game

### Description of the issue you are having

crashing

### Information

- [X] I have provided as much information as possible

**Comment by UnRealDinnerbone** [comment]
That is not the latest version

**Comment by Leclowndu93150** [comment]
do i need the latest version of forge ?

**Comment by Leclowndu93150** [comment]
[latest.log](https://github.com/nanite/Trenzalore/files/12643257/latest.log)

**Comment by UnRealDinnerbone** [comment]
Trenzalore not in the last log file? What is the issue you are having

**Comment by Leclowndu93150** [comment]
> Trenzalore not in the last log file? What is the issue you are having

so basicaly the game crashes at mod loading after moving from 3.0.1 to 3.3.0/1
with no crash report

**Comment by Leclowndu93150** [comment]
it is maybe an incompat with Connector, let me try without it 
edit: no it wasnt

**Comment by UnRealDinnerbone** [comment]
I think I see the issue

**Comment by Leclowndu93150** [comment]
im open for testing
edit: i just opened an issue for Compressium (i noticed it was the same org)

**Comment by UnRealDinnerbone** [comment]
Does the lastest version fix it?

**Comment by Leclowndu93150** [comment]
where can i find it
so if i read correctly, it now needs forge 47.1.46 ?

**Comment by Leclowndu93150** [comment]
![image](https://github.com/nanite/Trenzalore/assets/73310949/19549ae5-1606-45cf-968c-ebfb9ff6d5b7)
yeah so JAVD doesn't detect it

**Comment by Leclowndu93150** [comment]
it works thank you
